name: 'Setup unit test'
description: 'Composite actions to setup unit test'

runs:
  using: "composite"
  steps:
    - name: Build the docker-compose stack
      shell: bash
      run: |
        docker compose -f docker-compose-ci.yml up -d
        sleep 30

      
